### ISSUE TITLE
Issues with release 2.1.0

### ISSUE THREAD

**Issue by syphernl** [kitos9112/terragrunt-gitlab-cicd-config#150]
It seems that:

* The Github release doesn't contain assets (previous versions did)
* The `ghcr.io/kitos9112/terragrunt-gitlab-cicd-config:2.1.0` container reports that it is version `2.0.1`, but ISTM that this is due to the fact that the version in `Main.go` hasn't been bumped

**Comment by kitos9112** [comment]
I'm releasing a new version for this tool shortly today. Thanks for your contribution @syphernl

**Comment by kitos9112** [comment]
You can try out 3.0.1-alpha now
